package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	taboo "github.com/josecabralf/taboo/pkg/taboo"
)

// scaffoldInputs are the resolved values init renders the .taboo/ scaffold from:
// the config scalars plus the resolved agent profile whose credential keys seed
// .env.example.
type scaffoldInputs struct {
	// Workshop is the workshop name written to taboo.yaml.
	Workshop string
	// Base is the workshop base image written to taboo.yaml.
	Base string
	// Repo is the absolute host repository path written to taboo.yaml.
	Repo string
	// Agent is the chosen agent name written to taboo.yaml and named in .env.example.
	Agent string
	// Model is the chosen model written to taboo.yaml.
	Model string
	// Profile is the resolved agent profile whose CredentialEnvKeys seed .env.example.
	Profile taboo.AgentProfile
}

// scaffoldFile is one file in the scaffold plan: Path is relative to the .taboo/
// project dir, Contents is the rendered bytes.
type scaffoldFile struct {
	// Path is the file's location relative to the project dir, e.g. "taboo.yaml".
	Path string
	// Contents is the rendered file body.
	Contents []byte
}

// plan renders the three scaffold files in stable order (taboo.yaml, then
// .gitignore, then .env.example) and returns the first render error (only
// taboo.yaml, which marshals YAML, can fail).
func (in scaffoldInputs) plan() ([]scaffoldFile, error) {
	tabooYAML, err := renderTabooYAML(in)
	if err != nil {
		return nil, err
	}
	return []scaffoldFile{
		{Path: "taboo.yaml", Contents: tabooYAML},
		{Path: ".gitignore", Contents: renderGitignore()},
		{Path: ".env.example", Contents: renderEnvExample(in)},
	}, nil
}

// renderTabooYAML marshals the config scalars into a strict-loadable taboo.yaml,
// wrapping the document in a header comment and a commented footer that shows
// where the optional defaults: and workflows: blocks go. The marshaled struct
// guarantees the field names round-trip through taboo.LoadConfig.
func renderTabooYAML(in scaffoldInputs) ([]byte, error) {
	cfg := taboo.ProjectConfig{
		Workshop: in.Workshop,
		Base:     in.Base,
		Repo:     in.Repo,
		Agent:    in.Agent,
		Model:    in.Model,
		Strategy: "branch",
	}
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("render taboo.yaml: %w", err)
	}
	var buf bytes.Buffer
	buf.WriteString("# taboo.yaml — generated by `taboo init`.\n")
	buf.WriteString("# This is the single source of truth for this taboo project.\n")
	buf.WriteString("# Edit it directly; run `taboo doctor` to validate your changes.\n")
	buf.WriteString("\n")
	buf.Write(body)
	buf.WriteString("\n")
	buf.WriteString("# Optional blocks (uncomment and fill in as you need them):\n")
	buf.WriteString("#\n")
	buf.WriteString("# defaults:\n")
	buf.WriteString("#   branch-prefix: taboo/\n")
	buf.WriteString("#   timeout: 30m\n")
	buf.WriteString("#   max-iterations: 1\n")
	buf.WriteString("#\n")
	buf.WriteString("# workflows:\n")
	buf.WriteString("#   fix:\n")
	buf.WriteString("#     prompt: \"Fix the failing tests.\"\n")
	return buf.Bytes(), nil
}

// renderGitignore returns the .taboo/.gitignore body: a generated-by header
// comment followed by the four entries taboo writes runtime state to.
func renderGitignore() []byte {
	var buf bytes.Buffer
	buf.WriteString("# .gitignore — generated by `taboo init`.\n")
	buf.WriteString("# Runtime state taboo writes that should never be committed.\n")
	buf.WriteString("worktrees/\n")
	buf.WriteString(".workshop/\n")
	buf.WriteString(".env\n")
	buf.WriteString("logs/\n")
	return buf.Bytes()
}

// renderEnvExample returns the .taboo/.env.example body: a header naming the
// chosen agent and explaining taboo forwards only the keys present in the
// environment, then one KEY= line per credential env key the agent reads.
func renderEnvExample(in scaffoldInputs) []byte {
	var buf bytes.Buffer
	buf.WriteString("# .env.example — generated by `taboo init` for agent " + in.Agent + ".\n")
	buf.WriteString("# Copy this to .env, fill in the credential(s) you hold, then load them into\n")
	buf.WriteString("# your shell (e.g. `set -a; source .env; set +a`) before running taboo.\n")
	buf.WriteString("# taboo forwards only the keys present in the environment when it runs,\n")
	buf.WriteString("# so you only need to provide the one credential you use.\n")
	for _, key := range in.Profile.CredentialEnvKeys() {
		buf.WriteString(key + "=\n")
	}
	return buf.Bytes()
}

// writeScaffold creates projectDir and writes every planned file under it,
// creating parent dirs defensively. Dirs are 0750 and files 0600 per the
// repo's gosec posture.
func writeScaffold(projectDir string, files []scaffoldFile) error {
	if err := os.MkdirAll(projectDir, 0o750); err != nil {
		return fmt.Errorf("create %s: %w", projectDir, err)
	}
	for _, f := range files {
		dst := filepath.Join(projectDir, f.Path)
		if err := os.MkdirAll(filepath.Dir(dst), 0o750); err != nil {
			return fmt.Errorf("create dir for %s: %w", f.Path, err)
		}
		if err := os.WriteFile(dst, f.Contents, 0o600); err != nil {
			return fmt.Errorf("write %s: %w", f.Path, err)
		}
	}
	return nil
}
